use ecommerce_db;

INSERT INTO Supplier VALUES
(2,'Luke X. Hodges','Amet Risus Industries'),
(3,'Faith J. Keller','Vehicula Risus Industries'),
(4,'Darrel G. Silva','Dolor Dolor LLP'),
(5,'Alden X. Short','Pede Nec Corporation'),
(8,'Kylee H. Perkins','Augue Malesuada Incorporated'),
(11,'Joseph X. Phelps','Lacus Quisque Ltd'),
(12,'Ivan G. Lindsey','Mollis Phasellus PC'),
(13,'Theodore H. Hester','Sed Molestie Incorporated'),
(15,'Cooper Y. Washington','Lacus Mauris Non Corp.'),
(16,'Heidi G. Fields','A Industries'),
(19,'Zoe K. Richards','Purus In Incorporated'),
(20,'Jenna I. Sellers','Donec Incorporated'),
(21,'Cooper E. Duran','Eu Nibh LLP'),
(22,'Mason I. Tate','Cursus Inc.'),
(24,'Zena H. Blankenship','Ut Semper PC'),
(28,'Timothy V. Woodward','In LLC'),
(40,'Charlotte Z. Sutton','Molestie Dapibus Institute'),
(44,'Hector S. Shaffer','Enim Incorporated'),
(45,'Yolanda E. Thornton','Nulla Dignissim Consulting'),
(46,'Warren X. Shelton','Felis Ullamcorper Corp.'),
(47,'Warren Q. Cherry','Vivamus PC'),
(48,'Tallulah X. Lester','Amet Risus Donec Associates'),
(56,'Gabriel E. Combs','Montes Nascetur Consulting'),
(58,'Imelda N. George','Hendrerit Consectetuer Cursus Incorporated'),
(63,'Mira C. Roach','Fermentum Arcu Vestibulum Corporation'),
(64,'Trevor G. Dillard','Turpis Company'),
(66,'Armando K. Ayala','Ullamcorper Magna Incorporated'),
(67,'Sydney H. Fox','Vitae Limited'),
(76,'Kelly Y. Bridges','Aliquet Metus Industries'),
(82,'Cain F. Johns','Justo LLP'),
(87,'Nina K. Black','Tristique Neque Venenatis Corporation'),
(88,'Emerald L. Ramirez','Cras Dolor Foundation'),
(95,'Vincent N. Walker','Vivamus Molestie Inc.'),
(98,'Ramona Y. Daugherty','Pede Nec Ante Corporation'),
(99,'Geraldine','Dignissim Pharetra PC'),
(163,'Yuri','Enim Limited'),
(164,'Chaim','Auctor Vitae PC'),
(165,'Savannah','Ligula Nullam Feugiat Inc.'),
(166,'Gloria','Fringilla Ornare Placerat Inc.'),
(167,'Paloma','Dis Parturient Limited'),
(168,'Lisandra','Vitae Aliquet LLC'),
(169,'Colby','In Dolor Fusce Corporation'),
(170,'Philip','Mauris Company'),
(171,'Dean','Sed Nec Associates'),
(172,'Robin','Lorem Semper Foundation'),
(173,'Kiara','Erat Eget Associates'),
(174,'Ifeoma','Interdum Limited'),
(175,'Avram','Et Risus Quisque Foundation'),
(176,'Ivory','Volutpat Limited'),
(177,'Erasmus','Egestas Lacinia Ltd'),
(178,'Adam','Blandit PC'),
(179,'Sylvia','Vehicula Pellentesque Tincidunt Limited'),
(180,'Kasimir','Leo In Lobortis Institute'),
(181,'Ezra','Netus Et Industries'),
(182,'Sonia','Risus PC'),
(183,'Nevada','Mauris Ut Mi Corp.'),
(184,'Valentine','Arcu Vestibulum LLC'),
(185,'Buffy','Euismod Est LLC'),
(186,'Wade','Odio Vel Est Corporation'),
(187,'Orli','Orci Foundation'),
(188,'Erich','Aliquet Company'),
(189,'Hayfa','Ut Sem Nulla Corporation'),
(190,'Xaviera','Pellentesque LLP'),
(191,'Lynn','Cras Industries'),
(192,'Gabriel','Integer Limited'),
(193,'Harper','Ornare Consulting'),
(194,'Isaac','At Auctor Inc.'),
(195,'Hall','Auctor Velit Limited'),
(196,'Delilah','Elit Pellentesque Associates'),
(197,'Hanae','Mauris Ut Quam Company'),
(198,'Virginia','Nisl Quisque LLC'),
(199,'Hope','Nullam Velit Industries'),
(200,'Miranda','Ante Maecenas Institute'),
(201,'Cadman','Consectetuer Rhoncus Company'),
(202,'Belle','Massa Suspendisse PC'),
(203,'Randall','Risus Odio Auctor LLC'),
(204,'Meredith','Auctor Velit Associates'),
(205,'Tatyana','Mauris Vel Turpis Inc.'),
(206,'Salvador','Non Incorporated'),
(207,'Gabriel','Adipiscing Foundation'),
(208,'Leigh','Laoreet Incorporated'),
(209,'Lacey','Id Enim Associates'),
(210,'Stephen','Vel PC'),
(211,'Quemby','Sapien Cursus In Corporation'),
(212,'Kennedy','Felis Limited'),
(213,'Zeus','Interdum Enim Limited'),
(214,'Reese','Pede Nec Company'),
(215,'Brent','Consequat Dolor Consulting'),
(216,'Rana','Et Ipsum Cursus Ltd'),
(217,'Nolan','Risus Quis Corp.'),
(218,'Vielka','Lorem Ut Inc.'),
(219,'Adrienne','Cursus Diam Associates'),
(220,'Ifeoma','Non Leo Inc.'),
(221,'Galvin','Vestibulum Nec Euismod LLP'),
(222,'Bernard','Laoreet Ipsum Ltd'),
(223,'Maxine','Nulla Vulputate Corp.'),
(224,'Travis','Luctus Aliquet Foundation'),
(225,'Quinn','Ac Turpis Consulting'),
(226,'Lila','Eu Ltd'),
(227,'Montana','Non Justo Inc.');